# create a root dir with the name artifacts
artifacts_root: artifacts

# create sub folder ->  data ingestion inside root dir -> artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
